// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdayyazgurydouuoogyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkYXl5YXpndXJ5ZG91dW9vZ3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTM5MzMsImV4cCI6MjA1OTgyOTkzM30.GM0Bb0dfMyBn3gdM458AJRnk7pi7QRSweegKzpDmWrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);